version: "3.7"
services:
  app:
    build:
      args:
        user: thrivr
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: thrivr
    container_name: thrivr-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - thrivr

  db:
    image: mysql:5.7.16
    container_name: thrivr-db
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ../mysql_persist:/var/lib/mysql
    networks:
      - thrivr

  nginx:
    image: nginx:alpine
    container_name: thrivr-nginx
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - thrivr
  redis:
    image: redis:6.2
    container_name: redis
    restart: unless-stopped
    ports:
      - 6380:6379
    networks:
      - thrivr

networks:
  thrivr:
    driver: bridge